name: Upload Artifacts
on: push

jobs:
  artifact-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Create and Edit file
        run: |
          touch "my_artifact_file"
          echo "This will be uploaded" > my_artifact_file
      - name: Upload an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploaded_file_name
          path: /home/runner/github_actions_demo/github_actions_demo/my_artifact_file