name: third workflow demo
on: 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  gather-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output 'github' Context
        run: echo "${{ toJSON( github ) }}"