name: third workflow demo
on: 
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - demo_branch
      - 'dev_*'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
jobs:
  gather-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output 'github' Context
        run: echo "${{ toJSON( github ) }}"